import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { JsonLd } from "@/components/JsonLd";
import { ArticleBody, ArticleHeader, ArticleNavigation, AuthorBox, Breadcrumbs, FAQ, RelatedArticles, RelatedServices, ShareButtons, TableOfContents } from "@/components/article/ArticleComponents";
import { ARTICLES, BLOG_CATEGORIES, getArticle, getCategory, readingTime } from "@/lib/blog";
import { PROFILE } from "@/lib/data";
import { SITE_URL, buildMetadata } from "@/lib/seo";

export function generateStaticParams(){ return [...ARTICLES.map(a=>({slug:a.slug})),...BLOG_CATEGORIES.map(c=>({slug:c.slug}))]; }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const a=getArticle(slug); if(a) return {...buildMetadata({title:a.title,description:a.description,keywords:a.tags,path:`/blog/${a.slug}`}),openGraph:{title:a.title,description:a.description,url:`${SITE_URL}/blog/${a.slug}`,siteName:PROFILE.name,type:"article",publishedTime:a.published,modifiedTime:a.updated,authors:[PROFILE.name],tags:a.tags}}; const c=getCategory(slug); if(c) return buildMetadata({title:`${c.name} Engineering Articles | Ahmadullah Mukhlis`,description:c.description,keywords:[c.name,"software engineering"],path:`/blog/${c.slug}`}); return buildMetadata({title:"Article not found",description:"The requested article could not be found.",keywords:[],path:`/blog/${slug}`}); }

export default async function BlogSlugPage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const category=getCategory(slug); if(category){ const items=ARTICLES.filter(a=>a.category===category.slug); return <><Navbar/><main className="page-shell"><section className="mx-auto max-w-6xl px-5 pb-24 pt-12"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Articles",href:"/blog"},{label:category.name}]}/><h1 className="mt-10 text-5xl font-extrabold text-ink">{category.name}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{category.description}</p><div className="mt-12 grid gap-5 md:grid-cols-2">{items.map(a=><Link key={a.slug} href={`/blog/${a.slug}`} className="card-line p-6"><span className="font-mono text-xs text-gold">{readingTime(a)} min read</span><h2 className="mt-3 text-xl font-extrabold text-ink">{a.title}</h2><p className="mt-3 text-sm leading-7 text-muted">{a.excerpt}</p></Link>)}</div></section></main><Footer/></>; }
  const article=getArticle(slug); if(!article) notFound(); const categoryInfo=getCategory(article.category)!; const index=ARTICLES.findIndex(a=>a.slug===article.slug); const related=ARTICLES.filter(a=>a.slug!==article.slug&&a.category===article.category).slice(0,3); const url=`${SITE_URL}/blog/${article.slug}`; const breadcrumb=[{"@type":"ListItem",position:1,name:"Home",item:SITE_URL},{"@type":"ListItem",position:2,name:"Articles",item:`${SITE_URL}/blog`},{"@type":"ListItem",position:3,name:article.title,item:url}]; const schema={"@context":"https://schema.org","@graph":[{"@type":"BlogPosting",headline:article.title,description:article.description,datePublished:article.published,dateModified:article.updated,mainEntityOfPage:url,author:{"@type":"Person",name:PROFILE.name,url:`${SITE_URL}/author/ahmadullah-mukhlis`},publisher:{"@type":"Person",name:PROFILE.name,url:SITE_URL},keywords:article.tags.join(", "),articleSection:categoryInfo.name,inLanguage:"en"},{"@type":"BreadcrumbList",itemListElement:breadcrumb},{"@type":"FAQPage",mainEntity:article.faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]};
  return <><Navbar/><main className="page-shell"><JsonLd data={schema}/><article className="mx-auto max-w-6xl px-5 pb-24 pt-12"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Articles",href:"/blog"},{label:categoryInfo.name,href:`/blog/${categoryInfo.slug}`},{label:article.title}]}/><div className="mt-10"><ArticleHeader article={article} categoryName={categoryInfo.name}/></div><div className="mt-10 grid gap-12 lg:grid-cols-[240px_minmax(0,1fr)]"><div><div className="sticky top-24"><TableOfContents sections={article.sections}/></div></div><div className="min-w-0"><ArticleBody article={article}/><FAQ items={article.faqs}/><ShareButtons article={article}/><RelatedServices slug={article.relatedService}/><AuthorBox/><RelatedArticles articles={related}/><section className="mt-12  border border-rule p-6"><h2 className="text-xl font-extrabold">Building a payment platform, enterprise application, mobile app, or web system?</h2><p className="mt-3 text-sm leading-7 text-muted">Explore my engineering services or <Link className="text-gold" href="/contact">get in touch</Link> to discuss your software requirements.</p></section><ArticleNavigation previous={ARTICLES[index-1]} next={ARTICLES[index+1]}/></div></div></article></main><Footer/></>;
}
