services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: mukhlis:latest
    container_name: mukhlis
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
