import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Breadcrumbs } from "@/components/article/ArticleComponents";
import { ARTICLES, BLOG_CATEGORIES, readingTime } from "@/lib/blog";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Software Engineering Articles | Ahmadullah Mukhlis", description: "Practical articles on ISO 8583, payment systems, fintech, Laravel, Flutter, Next.js, React, DevOps, databases, and software architecture.", keywords: ["software engineering blog","ISO 8583 guides","fintech engineering","Laravel","Flutter","Next.js"], path: "/blog" });

export default function BlogPage() { return <><Navbar/><main className="page-shell"><section className="mx-auto max-w-6xl px-5 pb-20 pt-12"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Articles"}]}/><p className="mt-10 mono-label text-gold">Engineering knowledge</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold text-ink md:text-7xl">Technical articles for systems that must work.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Field notes and durable guides about financial messages, transaction reliability, application architecture, data, deployment, and production troubleshooting.</p><div className="mt-10 flex flex-wrap gap-2">{BLOG_CATEGORIES.map(c=><Link key={c.slug} href={`/blog/${c.slug}`} className="tag-pill">{c.name}</Link>)}</div><div className="mt-16 grid gap-5 md:grid-cols-2">{ARTICLES.map(a=><article key={a.slug} className="card-line flex flex-col p-6"><Link href={`/blog/${a.category}`} className="font-mono text-xs text-gold">{BLOG_CATEGORIES.find(c=>c.slug===a.category)?.name}</Link><h2 className="mt-3 text-xl font-extrabold leading-snug"><Link href={`/blog/${a.slug}`} className="text-ink hover:text-gold">{a.title}</Link></h2><p className="mt-3 flex-1 text-sm leading-7 text-muted">{a.excerpt}</p><div className="mt-5 flex justify-between font-mono text-xs text-muted"><time dateTime={a.updated}>{a.updated}</time><span>{readingTime(a)} min read</span></div></article>)}</div></section></main><Footer/></>; }
