export const BLOG_CATEGORIES = [
  { slug: "iso-8583", name: "ISO 8583", description: "Practical guidance on ISO 8583 messages, fields, transaction lifecycles, reversals, tracing, security boundaries, and switch integration. Network profiles differ, so every guide separates general concepts from implementation-specific rules." },
  { slug: "payment-systems", name: "Payment Systems", description: "Architecture and reliability guidance for gateways, switches, card flows, authorization, reconciliation, cryptographic boundaries, and highly available financial services." },
  { slug: "fintech", name: "Fintech", description: "Engineering patterns for trustworthy financial APIs and transaction platforms, with an emphasis on state, auditability, duplicate prevention, and failure recovery." },
  { slug: "laravel", name: "Laravel", description: "Production Laravel practices for API structure, authentication, queues, WebSockets, security, containers, observability, and maintainable business applications." },
  { slug: "flutter", name: "Flutter", description: "Architecture for maintainable Flutter mobile and desktop applications, including offline operation, synchronization, ERP workflows, deployment, and multi-currency data." },
  { slug: "nextjs", name: "Next.js", description: "Production Next.js guidance covering App Router boundaries, metadata, rendering, caching, API integration, container deployment, performance, and search visibility." },
  { slug: "react", name: "React", description: "Practical React application architecture for components, state, forms, routing, server communication, testing, accessibility, and runtime performance." },
  { slug: "devops", name: "DevOps", description: "Operational guides for Docker, Nginx, TLS, CI/CD, GitHub Actions, Jenkins, AWS deployment, monitoring, rollback, and resilient releases." },
  { slug: "software-architecture", name: "Software Architecture", description: "Clear trade-offs for APIs, monoliths, microservices, distributed communication, boundaries, reliability, and evolution of production systems." },
  { slug: "databases", name: "Databases", description: "Data modeling, constraints, transactions, indexing, caching, persistence, audit history, and reporting patterns for enterprise applications." },
] as const;

export type BlogCategory = (typeof BLOG_CATEGORIES)[number]["slug"];
export type ArticleSection = { id: string; title: string; paragraphs: string[]; bullets?: string[]; code?: { language: string; value: string }; callout?: string };
export type Article = {
  slug: string; title: string; description: string; excerpt: string; category: BlogCategory;
  tags: string[]; published: string; updated: string; featured?: boolean; sections: ArticleSection[];
  faqs: { question: string; answer: string }[]; relatedService: string;
};

const published = "2026-09-27";

function editorialContext(topic: string) {
  if (/ISO 8583|STAN|RRN|PIN Data|Processing Code|POS Entry|Track 2|Currency Codes/i.test(topic)) return "the processor profile, message encoding, conditional-field rules, and transaction lifecycle";
  if (/payment|issuer|acquirer|authorization|HSM|reconciliation|financial/i.test(topic)) return "the financial state machine, ledger evidence, participant contract, and recovery procedure";
  if (/Laravel/i.test(topic)) return "the HTTP boundary, application service, queue or event flow, database transaction, and operational runtime";
  if (/Flutter/i.test(topic)) return "the widget boundary, domain model, local store, synchronization contract, and server authority";
  if (/Next.js|React/i.test(topic)) return "the server/client boundary, data contract, rendering path, browser runtime, and deployment edge";
  if (/Docker|Nginx|CI\/CD|GitHub Actions|Jenkins|AWS|Redis/i.test(topic)) return "the build artifact, runtime configuration, network boundary, persistent state, and operational recovery path";
  return "the domain boundary, data owner, integration contract, failure mode, and operating procedure";
}

function expandPoint(point: string, topic: string, index: number, compact: boolean) {
  const context = editorialContext(topic);
  const leads = [
    "Treat this as an explicit contract rather than an informal convention.",
    "The implementation should make this behavior visible in code and operations.",
    "This decision needs a named owner and a testable rule.",
    "A production design must define the normal path and the recovery path together.",
  ];
  const checks = [
    "Document accepted input, the authoritative source, emitted output, and the state recorded before control crosses a network boundary.",
    "Validate it at the first trusted boundary, preserve the evidence needed for investigation, and reject ambiguous state instead of guessing.",
    "Test the successful case alongside malformed input, duplicate delivery, timeout, partial completion, restart, and delayed response scenarios.",
    "Expose safe correlation identifiers, latency, outcome, and state transitions so support teams can diagnose a failure without accessing sensitive payloads.",
  ];
  const closing = compact
    ? "The network specification remains authoritative when a participant defines a different format or lifecycle."
    : `Review the effect across ${context}. A local shortcut is unsafe when it moves inconsistency into another service, a later retry, reconciliation, or a manual support process.`;
  return `${point}. ${leads[index % leads.length]} ${checks[index % checks.length]} ${closing}`;
}

function section(title: string, topic: string, points: string[], options: Partial<ArticleSection> = {}): ArticleSection {
  const id = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const compact = topic.startsWith("ISO 8583 Explained:");
  return {
    id, title,
    paragraphs: [
      `${title} is a practical part of ${topic}, not an isolated implementation detail. A reliable design gives the concept a clear owner, defines the data it accepts, records each state change, and makes failures visible. The exact protocol or framework configuration may vary, but the engineering requirement remains the same: preserve intent and make the result explainable.`,
      `In production, the useful questions are where validation occurs, which system is authoritative, how a retry is recognized, and what operators can inspect after a timeout. Treating these questions as architecture decisions prevents accidental coupling and reduces the chance that a transient network failure becomes inconsistent business data.`,
      ...points.map((point, index) => expandPoint(point, topic, index, compact)),
    ],
    bullets: points,
    ...options,
  };
}

function makeArticle(input: Omit<Article, "published" | "updated" | "sections" | "faqs"> & { outline: [string, string[]][]; intro?: string; code?: ArticleSection["code"]; note?: string }): Article {
  const sections = input.outline.map(([title, points], index) => section(title, input.title, points, {
    ...(index === 0 && input.intro ? { paragraphs: [input.intro, `The sections below connect the concept to validation, state management, operations, and failure recovery. Examples are intentionally fictional and must be adapted to the contract published by the relevant framework, processor, or network.`] } : {}),
    ...(index === 1 && input.code ? { code: input.code } : {}),
    ...(index === input.outline.length - 1 && input.note ? { callout: input.note } : {}),
  }));
  return {
    ...input, published, updated: published, sections,
    faqs: [
      { question: `What is the main design concern in ${input.title.replace(/:.*$/, "")}?`, answer: `Correctness under normal and failure conditions. Define ownership, validate at the boundary, persist meaningful state, and make retries and operator investigation predictable.` },
      { question: "Should the examples be copied directly into production?", answer: "No. They illustrate architecture and must be adapted, reviewed, tested, and secured for the actual framework version, business rules, and integration contract." },
      { question: "How should teams test this design?", answer: "Combine unit tests for rules, integration tests for boundaries, and scenario tests for timeouts, duplicates, partial failure, recovery, and observability." },
    ],
  };
}

const definitions: Array<Parameters<typeof makeArticle>[0]> = [
  {
    slug: "iso-8583-guide", title: "ISO 8583 Explained: Complete Guide to Payment Message Structure and Transaction Processing",
    description: "Learn how ISO 8583 payment messages work, including MTIs, bitmaps, data elements, transaction flows, response codes, reversals, STAN, RRN, terminal information, PIN data, and payment-switch processing.",
    excerpt: "A system-level guide to ISO 8583 message anatomy, participants, transaction flows, reliability controls, security boundaries, testing, and reconciliation.", category: "iso-8583", tags: ["ISO 8583", "payment switch", "card payments", "fintech architecture"], featured: true, relatedService: "fintech",
    intro: "ISO 8583 is a family of standards used to exchange card-originated financial transaction messages. It provides a message structure—an MTI, one or more bitmaps, and data elements—but a network profile determines the precise field encodings, allowed values, framing, and transaction rules. Two systems can both use ISO 8583 and still require an explicit mapping layer.",
    outline: [
      ["What ISO 8583 is and why it is used", ["Common language between heterogeneous financial systems", "Compact, structured messages for online authorization and related operations", "A standard family with processor- and network-specific dialects"]],
      ["The payment ecosystem", ["Cardholder initiates an instruction at a POS, ATM, or mobile channel", "Acquirer accepts the transaction and a switch routes it", "Network connects participants; issuer or authorization system decides", "Responses return through the same controlled path"]],
      ["Message anatomy: MTI, bitmap, and fields", ["MTI describes version, class, function, and origin", "Primary and optional secondary bitmap signal present fields", "Data elements carry amount, trace, merchant, terminal, currency, and security data"]],
      ["Core transaction identifiers and values", ["DE3 processing code expresses operation and account context", "DE4 carries amount in currency minor units", "DE11 STAN supports local tracing; DE37 RRN supports wider retrieval", "DE22 entry mode, DE41 terminal, DE42 merchant, and DE49 currency add context"]],
      ["Purchase and balance-inquiry flows", ["Validate channel request before packing", "Persist an internal transaction identity and state", "Correlate response using the integration contract", "Return a stable, sanitized result to the channel"]],
      ["Reversals and timeouts", ["A timeout is an unknown outcome, not an automatic decline", "Reference the original transaction correctly", "Make automated and manual reversals idempotent", "Reconcile unresolved states rather than guessing"]],
      ["Network management messages", ["Sign-on establishes operational readiness", "Echo verifies connectivity without proving end-to-end authorization", "Key-change and cutover processes belong behind controlled security and operations boundaries"]],
      ["Response codes", ["DE39 communicates the result defined by the network profile", "00 commonly means approval and 05 commonly means do not honor", "Never expose raw internal or issuer detail when a safer channel message is appropriate"]],
      ["PIN data, HSMs, and security", ["Never log PAN, track data, PIN blocks, or cryptographic keys", "Use an HSM for controlled cryptographic operations", "Apply PCI-aligned masking, retention, access control, and key lifecycle practices", "Keep PIN translation and verification outside general application code"]],
      ["Logging, idempotency, and duplicates", ["Log safe identifiers, timing, route, state transition, and sanitized error class", "Enforce an idempotency boundary with atomic persistence", "Distinguish a repeated delivery from a new financial instruction"]],
      ["Reconciliation and testing", ["Compare internal records against processor and settlement evidence", "Test approved, declined, timeout, late-response, duplicate, malformed, and reversal scenarios", "Use simulators with fictional data and deterministic assertions"]],
      ["Common implementation mistakes", ["Assuming one dialect is universal", "Using STAN as the only global identifier", "Treating socket success as transaction success", "Retrying financial requests without duplicate controls", "Logging sensitive fields or relying on logs as a ledger"]],
    ],
    code: { language: "text", value: "MTI: 0200\nBitmap: [DE3, DE4, DE7, DE11, DE22, DE37, DE41, DE42, DE49]\nDE3: 000000\nDE4: 000000012500   # 125.00 in a two-decimal currency\nDE11: 482731\nDE37: 260927482731\nDE41: TERM0001\nDE42: MERCHANT000001\nDE49: 840\n# Fictional, non-production values; encoding depends on the network profile." },
    note: "Never place real PANs, PIN blocks, keys, credentials, or production banking data in examples, tests, analytics, or general application logs.",
  },
  { slug: "iso-8583-mti", title: "ISO 8583 MTI Explained: Understanding Message Type Indicators", description: "Understand the four ISO 8583 MTI digits, message classes, request and response functions, and common MTIs such as 0100, 0200, 0400, and 0800.", excerpt: "Decode ISO 8583 Message Type Indicators and understand what each digit contributes to message meaning.", category: "iso-8583", tags: ["ISO 8583", "MTI", "financial messages"], relatedService: "fintech", outline: [["The four MTI digits", ["Digit 1 identifies the ISO version", "Digit 2 identifies the message class", "Digit 3 indicates function such as request, response, advice, or notification", "Digit 4 identifies message origin"]], ["Common MTIs", ["0100/0110 authorization request and response", "0200/0210 financial request and response", "0400/0410 reversal request and response", "0800/0810 network-management request and response"]], ["Requests, responses, and advice", ["A request expects a decision", "A response carries the corresponding result", "Advice reports an action already taken and has different recovery semantics"]], ["Dialect differences", ["Confirm supported MTIs in the network specification", "Do not infer settlement behavior from an MTI alone", "Validate direction and required fields per route"]]] },
  { slug: "iso-8583-data-elements", title: "ISO 8583 Data Elements Explained: A Practical Field-by-Field Guide", description: "A practical guide to important ISO 8583 data elements, their purpose, typical formats, fictional examples, security concerns, and integration pitfalls.", excerpt: "Field-by-field guidance for the ISO 8583 elements engineers most often encounter.", category: "iso-8583", tags: ["ISO 8583", "data elements", "payment messages"], relatedService: "fintech", outline: [["Account and transaction fields", ["DE2 PAN: variable numeric; tokenize and mask", "DE3 processing code: fixed numeric; map transaction and account types", "DE4 amount: fixed numeric minor units; never use floating point", "DE49 currency: ISO 4217 numeric code interpreted with currency rules"]], ["Date and trace fields", ["DE7 transmission date/time", "DE11 STAN for system trace", "DE12/DE13 local time and date", "DE37 RRN for retrieval", "DE38 authorization identification response"]], ["Acceptance context", ["DE18 merchant category", "DE22 POS entry mode", "DE25 POS condition", "DE41 terminal ID", "DE42 merchant ID", "DE43 card acceptor name/location"]], ["Routing and account fields", ["DE32 acquiring institution ID", "DE102 account identification 1", "DE103 account identification 2", "Lengths and meaning are profile-specific"]], ["Sensitive and extended data", ["DE35 Track 2 must not be logged", "DE48 private additional data requires an explicit subfield contract", "DE52 encrypted PIN data belongs at an HSM boundary", "DE55 EMV data is structured TLV, not free text", "DE90 references the original transaction"]], ["Response and implementation checks", ["DE39 is interpreted through the network code list", "Validate type, length, encoding, padding, and conditional presence", "Keep fictional examples in test fixtures and redact diagnostic output"]]] },
  { slug: "iso-8583-response-codes", title: "ISO 8583 Response Codes: How Transaction Results Are Communicated", description: "Learn how ISO 8583 DE39 communicates transaction outcomes, what common response codes mean, and how to troubleshoot results safely.", excerpt: "Interpret response codes without confusing network conventions with universal rules.", category: "iso-8583", tags: ["ISO 8583", "DE39", "response codes"], relatedService: "fintech", outline: [["What DE39 communicates", ["A compact result from the deciding system", "Meaning is governed by the network specification", "Channel messages should be mapped without leaking sensitive detail"]], ["Common examples", ["00 approval", "05 do not honor", "12 invalid transaction", "13 invalid amount", "14 invalid account or card number", "30 format error", "51 insufficient funds", "54 expired card", "55 incorrect PIN", "57/58 transaction not permitted", "61 limit exceeded", "65 activity limit exceeded", "91 issuer unavailable", "96 system malfunction"]], ["Troubleshooting by layer", ["Validate the outbound request before blaming the issuer", "Correlate safe identifiers and timestamps", "Distinguish business declines from technical failures", "Check late responses and reversal state"]]] },
  { slug: "iso-8583-reversal", title: "ISO 8583 Reversal Transactions: How Failed and Timed-Out Payments Are Recovered", description: "Understand ISO 8583 reversal requests and advice, timeout recovery, original transaction references, duplicate handling, idempotency, and reconciliation.", excerpt: "Design reversal processing for uncertain outcomes, duplicates, and operational recovery.", category: "iso-8583", tags: ["ISO 8583", "reversal", "timeouts", "reconciliation"], relatedService: "fintech", outline: [["Why reversals exist", ["The issuer may process a request whose response is lost", "A terminal or acquirer may be unable to complete the customer interaction", "A reversal attempts to neutralize the original financial effect"]], ["Timeout sequence", ["POS → acquirer → switch → issuer", "Issuer response is delayed or lost", "Acquirer records an unknown outcome", "Reversal travels toward the original decision point"]], ["Original transaction reference", ["Carry the fields required by the profile, commonly including DE90", "Preserve original MTI, trace, transmission time, and institution context", "Do not construct references from mutable display data"]], ["Automatic and manual recovery", ["Automate only from durable state", "Protect manual actions with authorization and audit", "Handle request and advice semantics separately"]], ["Duplicates and reconciliation", ["Use an idempotent reversal identity", "Return the known result for duplicate delivery", "Reconcile pending, late, unmatched, and rejected reversals"]]] },
  { slug: "iso-8583-stan-vs-rrn", title: "STAN vs RRN in ISO 8583: What’s the Difference?", description: "Compare ISO 8583 STAN in DE11 with RRN in DE37, including generation, scope, uniqueness, lookup, troubleshooting, and reconciliation.", excerpt: "A precise comparison of two identifiers that are often incorrectly treated as interchangeable.", category: "iso-8583", tags: ["STAN", "RRN", "DE11", "DE37"], relatedService: "fintech", outline: [["DE11: STAN", ["Usually six numeric digits", "Generated within a system or channel scope", "May roll over and therefore is not globally unique", "Useful for short-window tracing"]], ["DE37: RRN", ["Retrieval reference number used across a broader transaction path", "Often twelve characters, subject to the profile", "Useful in support and reconciliation", "Generation ownership must be explicit"]], ["Comparison and lookup", ["Store both as strings to preserve leading zeros", "Search with date, route, terminal, and amount context", "Keep a separate immutable internal transaction ID", "Never assume either value alone is universally unique"]]] },
  { slug: "iso-8583-field-3-processing-code", title: "ISO 8583 Field 3: Processing Code Explained", description: "Understand ISO 8583 DE3 processing codes, transaction and account type segments, routing decisions, examples, and profile-specific differences.", excerpt: "How DE3 expresses transaction intent and influences validation and routing.", category: "iso-8583", tags: ["ISO 8583", "DE3", "processing code"], relatedService: "fintech", outline: [["Processing-code structure", ["Common profiles divide six digits into transaction, source-account, and destination-account segments", "Values are network-defined, not universal"]], ["Routing and validation", ["Map external values to internal enums", "Reject unsupported combinations early", "Keep routing rules configuration-driven and versioned"]], ["Fictional examples", ["000000 may represent purchase from a default account", "310000 may represent balance inquiry", "Transfer values often encode both account sides", "Confirm every value against the processor guide"]]] },
  { slug: "iso-8583-field-4-amount", title: "ISO 8583 Field 4: Transaction Amount and Minor Units", description: "Learn how ISO 8583 DE4 represents transaction amounts, minor currency units, decimal handling, rounding, currency interaction, and common mistakes.", excerpt: "Represent payment amounts exactly without floating-point or currency errors.", category: "iso-8583", tags: ["ISO 8583", "DE4", "money"], relatedService: "fintech", outline: [["Amount representation", ["DE4 is commonly a twelve-digit numeric field", "The value is normally expressed in currency minor units", "125.00 becomes 000000012500 for a two-decimal currency"]], ["Currency and rounding", ["Interpret DE4 together with DE49", "Use an integer or decimal money type, never binary floating point", "Apply one documented rounding rule at a controlled boundary"]], ["Common mistakes", ["Assuming every currency has two decimals", "Formatting separators into the wire value", "Losing leading zeros", "Converting currencies without an explicit exchange operation"]]] },
  { slug: "iso-8583-field-11-stan", title: "ISO 8583 Field 11: STAN Generation and Transaction Tracing", description: "Design ISO 8583 DE11 STAN generation with safe rollover, collision handling, logging, and transaction tracing.", excerpt: "Generate and use six-digit trace numbers without treating them as permanent global IDs.", category: "iso-8583", tags: ["ISO 8583", "DE11", "STAN"], relatedService: "fintech", outline: [["Generation and scope", ["Commonly six numeric digits", "Define whether the counter is per terminal, node, institution, or route", "Preserve leading zeros"]], ["Rollover and collisions", ["A one-million-value namespace necessarily repeats", "Combine STAN with date and route context", "Use atomic allocation across active nodes"]], ["Tracing safely", ["Persist a separate internal ID", "Log STAN with sanitized routing and timing context", "Design support searches for repeated values"]]] },
  { slug: "iso-8583-field-22-pos-entry-mode", title: "ISO 8583 Field 22: POS Entry Mode Explained", description: "Understand ISO 8583 DE22 for manual, magnetic-stripe, chip, contactless, and fallback entry, with network-specific encoding cautions.", excerpt: "Use entry-mode information to validate terminal context and risk signals.", category: "iso-8583", tags: ["ISO 8583", "DE22", "POS"], relatedService: "fintech", outline: [["What entry mode describes", ["How account data was captured", "Often includes PIN-capability context", "Encoding varies by network and version"]], ["Common concepts", ["Manual entry", "Magnetic stripe", "EMV chip", "Contactless", "Fallback after chip-read failure"]], ["Validation and risk", ["Cross-check terminal capabilities", "Do not silently rewrite fallback indicators", "Retain safe context for dispute investigation"]]] },
  { slug: "iso-8583-field-35-track-2", title: "ISO 8583 Field 35: Track 2 Data and PCI-Safe Handling", description: "A defensive guide to ISO 8583 DE35 Track 2 structure, PAN, expiry, service code, discretionary data, masking, and secure processing.", excerpt: "Understand Track 2 conceptually while keeping sensitive authentication data out of logs and storage.", category: "iso-8583", tags: ["ISO 8583", "DE35", "PCI DSS"], relatedService: "fintech", outline: [["Conceptual structure", ["PAN identifies the payment account", "A separator precedes expiry and service code", "Discretionary data is scheme- and issuer-controlled"]], ["Security boundary", ["Treat full track data as highly sensitive", "Never place it in application logs, analytics, URLs, or exception messages", "Restrict retention according to the applicable security standard"]], ["Implementation discipline", ["Parse only at the controlled boundary that needs it", "Mask display values", "Use fictional tokens in tests", "Verify encoding and length from the network contract"]]], note: "This guide intentionally excludes usable card data. Security controls and applicable PCI requirements take precedence over diagnostic convenience." },
  { slug: "iso-8583-field-37-rrn", title: "ISO 8583 Field 37: Retrieval Reference Number Explained", description: "Learn how ISO 8583 DE37 RRN supports transaction tracing, reconciliation, support investigations, and correlation with STAN.", excerpt: "Design RRN generation, storage, and lookup for reliable transaction operations.", category: "iso-8583", tags: ["ISO 8583", "DE37", "RRN"], relatedService: "fintech", outline: [["Purpose and ownership", ["Supports retrieval across participating systems", "Generation format and owner are profile-specific", "Preserve the exact string"]], ["Operational use", ["Combine RRN with date, amount, merchant, and route", "Index it for support and reconciliation", "Handle missing and duplicate values explicitly"]], ["Relationship with STAN", ["STAN is normally narrower and shorter-lived", "RRN often spans a broader path", "Neither replaces the internal transaction ID"]]] },
  { slug: "iso-8583-field-41-terminal-id", title: "ISO 8583 Field 41: Terminal Identification in Payment Systems", description: "Understand ISO 8583 DE41 terminal IDs for routing, audit, merchant configuration, security, and troubleshooting.", excerpt: "Manage terminal identities as controlled configuration, not trusted free-form input.", category: "iso-8583", tags: ["ISO 8583", "DE41", "terminal ID"], relatedService: "fintech", outline: [["Terminal identity", ["Identifies the acceptance device within the acquiring domain", "Format and length depend on the profile", "Links operational configuration to a physical or logical channel"]], ["Routing and audit", ["Resolve terminal-to-merchant relationships centrally", "Retain configuration history", "Use terminal context in safe audit events"]], ["Security and common faults", ["Authenticate the channel independently of a claimed DE41", "Detect unknown, disabled, or mismatched terminals", "Avoid hard-coded routing tables"]]] },
  { slug: "iso-8583-field-42-merchant-id", title: "ISO 8583 Field 42: Merchant Identification Explained", description: "Learn how ISO 8583 DE42 identifies merchants in acquiring, settlement, configuration, audit, and troubleshooting workflows.", excerpt: "Keep merchant identities consistent across acceptance, routing, and settlement systems.", category: "iso-8583", tags: ["ISO 8583", "DE42", "merchant ID"], relatedService: "fintech", outline: [["Merchant identification", ["Identifies the card acceptor in the acquiring context", "Length and padding rules are profile-specific", "A merchant may have multiple terminals"]], ["Settlement and configuration", ["Map merchant identity to settlement and risk configuration", "Version changes and effective dates", "Validate terminal-merchant relationships"]], ["Common problems", ["Whitespace and padding mismatches", "Stale onboarding data", "Confusing display names with stable IDs", "Uncoordinated identifier migration"]]] },
  { slug: "iso-8583-field-49-currency-code", title: "ISO 8583 Field 49: Currency Codes and Minor Units", description: "Understand ISO 8583 DE49, ISO 4217 numeric currency codes, minor units, multi-currency processing, and settlement-currency differences.", excerpt: "Interpret transaction currency correctly and keep it distinct from settlement or reporting currency.", category: "iso-8583", tags: ["ISO 8583", "DE49", "ISO 4217"], relatedService: "fintech", outline: [["Transaction currency", ["DE49 commonly carries an ISO 4217 numeric code", "Use a controlled currency table", "Interpret DE4 using that currency's minor-unit rules"]], ["Multi-currency boundaries", ["Preserve the original transaction amount and currency", "Store exchange rate, source, time, and converted result only for explicit conversion", "Do not silently overwrite original money"]], ["Settlement differences", ["Transaction and settlement currency may differ", "Model both amounts independently", "Reconcile fees and conversion adjustments from authoritative evidence"]]] },
  { slug: "iso-8583-field-52-pin-data", title: "ISO 8583 Field 52: PIN Data and Secure PIN Processing", description: "A defensive architecture guide to encrypted PIN blocks, HSM boundaries, ZPK concepts, key lifecycles, KCVs, and secure transport.", excerpt: "Understand PIN-processing boundaries without exposing keys or teaching security-control bypasses.", category: "iso-8583", tags: ["ISO 8583", "DE52", "HSM", "PIN security"], relatedService: "fintech", outline: [["Encrypted PIN blocks", ["DE52 carries protected PIN-related data, not a clear PIN", "PIN-block format is agreed by participants", "General application services must not decrypt or log it"]], ["HSM boundary", ["HSMs isolate cryptographic keys and sensitive operations", "Applications send authorized commands through a narrow integration", "ZPK and related key concepts belong to a managed hierarchy"]], ["Key lifecycle and KCV", ["Use controlled generation, distribution, activation, rotation, revocation, and destruction", "A KCV helps confirm key identity without revealing the key", "Apply dual control and separation of duties where required"]], ["Secure integration", ["Authenticate and encrypt transport", "Restrict commands by service identity", "Audit outcomes without sensitive payloads", "Fail closed and surface actionable operational alarms"]]], note: "No real key, PIN, PIN block, or production cryptographic material belongs in source code, configuration repositories, tickets, examples, or logs." },
];

const supporting: Array<[string,string,string,BlogCategory,string[],string,string[][]]> = [
  ["payment-switch-architecture","Payment Switch Architecture: How Financial Transactions Are Routed Reliably","A practical payment-switch architecture covering channels, routing, HSMs, state, queues, timeouts, reversals, reconciliation, monitoring, and high availability.","payment-systems",["payment switch","fintech","high availability"],"fintech",[["Channels, gateway, and switch boundaries","Normalize channel input|Authenticate connections|Keep protocol translation separate from business routing"],["Routing and authorization","Choose an issuer or network deterministically|Version routing tables|Record every decision"],["State, queues, and data","Use a durable transaction state machine|Use queues for asynchronous work, not hidden synchronous waits|Keep audit records append-oriented"],["Timeouts, retry, and reversal","Treat timeout as unknown|Retry only idempotent operations|Trigger profile-compliant recovery"],["HSM and security boundary","Isolate key operations|Minimize sensitive data exposure|Audit commands and access"],["Reconciliation and operational control","Separate online processing from end-of-day comparison|Retain immutable source evidence|Route exceptions through an audited workflow"],["Monitoring and high availability","Measure latency by hop|Run redundant stateless nodes|Plan database failover and reconciliation"]]],
  ["card-payment-transaction-flow","Card Payment Transaction Flow: From POS Terminal to Issuer and Back","Follow a card payment from cardholder and terminal through merchant, acquirer, switch, network, issuer, clearing, and settlement.","payment-systems",["card payments","authorization","settlement"],"fintech",[["Authorization participants","Cardholder and merchant|Terminal and acquirer|Switch or network|Issuer and authorization engine"],["Request and response path","Capture payment intent|Protect and route data|Apply issuer decision|Return an approved or declined result"],["Clearing and settlement","Authorization reserves or confirms capacity|Clearing presents financial records|Settlement moves net funds|Exceptions feed reconciliation"]]],
  ["issuer-vs-acquirer","Issuer vs Acquirer: Roles in Card Payment Processing","Compare issuers and acquirers across customers, risk, authorization, merchant acceptance, settlement, disputes, and system responsibilities.","payment-systems",["issuer","acquirer","card payments"],"fintech",[["Issuer responsibilities","Serves the cardholder|Maintains account and limits|Authorizes transactions|Manages cardholder risk"],["Acquirer responsibilities","Serves the merchant|Connects acceptance channels|Submits transactions|Supports merchant settlement"],["Shared transaction lifecycle","Exchange messages through networks|Handle exceptions and disputes|Reconcile independent records"]]],
  ["how-payment-gateways-work","How Payment Gateways Work: Architecture, APIs, Security and Reliability","Understand gateway architecture from checkout and APIs through processors, switches, issuers, webhooks, idempotency, and reconciliation.","payment-systems",["payment gateway","API","webhooks"],"fintech",[["Checkout and API boundary","Tokenize sensitive payment data|Authenticate merchant requests|Validate amount and order context"],["Processing path","Gateway orchestrates|Processor or switch routes|Issuer decides|Gateway maps a stable merchant response"],["Webhooks and idempotency","Sign webhook deliveries|Retry with backoff|Deduplicate by event ID|Make merchant APIs idempotent"],["Reconciliation","Compare gateway, processor, and ledger records|Investigate mismatches|Never use webhook receipt as the sole ledger"]]],
  ["payment-reversal-flow","Payment Reversal Flow: Recovering Timed-Out Financial Transactions","Design application-level and switch-level reversal handling for unknown outcomes, late responses, duplicates, and reconciliation.","payment-systems",["reversal","payment reliability","timeouts"],"fintech",[["Unknown outcomes","Separate declined from timed out|Persist state before external calls|Retain correlation identifiers"],["Application-level recovery","Expose pending state safely|Schedule controlled status checks|Prevent a second purchase from masquerading as retry"],["Switch-level reversal","Reference the original instruction|Deduplicate reversal messages|Track acknowledgment and final evidence"]]],
  ["authorization-clearing-settlement","Authorization, Clearing and Settlement Explained","Understand the distinct goals, timing, records, and failure modes of payment authorization, clearing, and settlement.","payment-systems",["authorization","clearing","settlement"],"fintech",[["Authorization","Real-time decision|Checks credentials, status, risk, and funds|Does not by itself describe final interbank movement"],["Clearing","Exchanges presentment and fee records|Calculates obligations|Handles adjustments and chargebacks"],["Settlement","Moves net or gross value between participants|Uses settlement accounts and cutoffs|Requires financial reconciliation"]]],
  ["hsm-payment-systems","Hardware Security Modules in Payment Systems: What Software Engineers Need to Know","A defensive guide to HSM key isolation, PIN processing, cryptographic operations, key lifecycle, integration boundaries, and audit.","payment-systems",["HSM","cryptography","PIN security"],"fintech",[["Why HSMs exist","Keep key material inside a hardened boundary|Perform sensitive operations without exporting keys|Enforce policy and audit"],["Software integration boundary","Use an authenticated client service|Allow only required commands|Classify timeouts separately from cryptographic rejection"],["Key lifecycle","Generate and import under controlled procedures|Activate and rotate deliberately|Retire and destroy with evidence"]]],
  ["idempotency-financial-transactions","Idempotency in Financial Transactions: Preventing Duplicate Payments","Implement idempotency keys, database constraints, transaction states, network retry handling, and safe financial APIs.","fintech",["idempotency","financial APIs","database constraints"],"fintech",[["Idempotency contract","Scope keys to caller and operation|Bind the key to a request fingerprint|Return the previously recorded result"],["Atomic persistence","Create the key record and transaction in one database transaction|Use a unique constraint|Lock or compare-and-set state transitions"],["Network retries","Retry transport failures with the same key|Do not retry unknown financial outcomes as new instructions|Reconcile late responses"]]],
  ["payment-reconciliation","Payment Reconciliation: Matching Transactions, Settlement and Exceptions","Design reconciliation across an internal ledger, processor reports, settlement files, duplicates, missing records, and exception workflows.","payment-systems",["reconciliation","settlement","ledger"],"fintech",[["Sources of truth","Internal transaction journal|Processor or network report|Settlement evidence|Bank account or ledger posting"],["Matching strategy","Normalize identifiers and currency|Match exact records first|Use controlled composite matching|Preserve source files immutably"],["Exception workflow","Classify missing, duplicate, amount, status, and fee mismatches|Assign and audit resolution|Never silently force balance"]]],
  ["high-availability-payment-systems","High-Availability Payment Systems: Reliability and Disaster Recovery","Plan load balancing, redundancy, failover, databases, queues, health checks, observability, disaster recovery, RTO, and RPO.","payment-systems",["high availability","disaster recovery","payments"],"fintech",[["Redundant application path","Run multiple stateless instances|Use health-aware load balancing|Remove unhealthy nodes without losing transaction state"],["Data and queue strategy","Choose consistency deliberately|Replicate durable state|Design consumers for redelivery"],["Recovery objectives","RTO describes acceptable restoration time|RPO describes acceptable data-loss window|Test failover and restoration rather than trusting diagrams"]]],
  ["laravel-production-architecture","Laravel Production Architecture: Building Reliable APIs and Enterprise Applications","Structure production Laravel applications with services, validation, authentication, queues, events, Redis, caching, APIs, logging, Docker, Nginx, and CI/CD.","laravel",["Laravel","API architecture","enterprise software"],"api-development",[["Application boundaries","Keep controllers focused on HTTP|Put business workflows in explicit application services|Use repositories only where they create a real abstraction"],["Validation and authorization","Use form requests for shape|Use policies for permissions|Enforce invariants again at the domain or database boundary"],["Queues, events, and Redis","Queue slow side effects|Make jobs idempotent|Set bounded retries and failed-job alerts|Treat cache as disposable"],["Database and API design","Use transactions for atomic changes|Add constraints and indexes|Version contracts deliberately|Paginate collections"],["Testing and observability","Test policies and business workflows independently|Use integration tests for database and queue boundaries|Correlate HTTP requests, jobs, and external calls"],["Production runtime","Run PHP-FPM behind Nginx|Supervise queue workers and scheduler|Emit structured logs and health signals"],["Delivery","Build immutable images|Run tests and migrations safely|Keep rollback compatible with schema changes"]]],
  ["laravel-sanctum-authentication","Laravel Sanctum Authentication for SPAs and APIs","Use Laravel Sanctum safely for first-party SPAs and API tokens, including cookies, CSRF, abilities, revocation, and deployment boundaries.","laravel",["Laravel Sanctum","authentication","SPA"],"api-development",[["SPA cookie authentication","Use stateful domains|Protect login with CSRF|Use secure, HTTP-only cookies|Configure trusted origins precisely"],["API tokens","Issue narrowly scoped tokens|Store only hashed tokens|Expose revocation and device management|Do not treat abilities as the only authorization layer"],["Production checks","TLS everywhere|Rate-limit sensitive endpoints|Rotate sessions after authentication|Log safe security events"]]],
  ["laravel-socialite","Laravel Socialite: OAuth Login Architecture","Design Laravel OAuth login with Socialite, secure state validation, account linking, provider callbacks, and safe token handling.","laravel",["Laravel Socialite","OAuth","authentication"],"api-development",[["Redirect and callback flow","Create a provider authorization request|Validate callback state|Exchange the code server-side|Fetch the permitted identity claims"],["Account linking","Require authenticated confirmation for linking|Handle provider email changes|Prevent duplicate local identities"],["Token security","Request minimum scopes|Encrypt retained refresh tokens|Never expose provider secrets to the browser"]]],
  ["laravel-reverb-websocket","Laravel Reverb and WebSockets in Production","Deploy Laravel Reverb with broadcasting, private-channel authentication, Echo clients, reverse proxies, TLS, scaling, and connection troubleshooting.","laravel",["Laravel Reverb","WebSockets","Laravel Echo"],"cloud-devops",[["Broadcast architecture","Publish domain events after committed state|Authorize private and presence channels|Keep channel names stable"],["Reverse proxy deployment","Forward upgrade headers|Configure idle timeouts|Terminate TLS consistently|Expose an explicit health path"],["Common failures","Origin mismatch|Invalid channel auth|Proxy stripping upgrade headers|Workers broadcasting before commit"]]],
  ["laravel-queues-production","Laravel Queues in Production: Workers, Retries and Failed Jobs","Operate Laravel queue workers with Redis, bounded retry, timeouts, supervision, idempotent jobs, and failed-job recovery.","laravel",["Laravel queues","Redis","background jobs"],"cloud-devops",[["Job design","Pass stable identifiers instead of large models|Make side effects idempotent|Define timeout and retry policy per job"],["Worker operation","Supervise long-running workers|Restart after deployment|Separate queues by latency and priority"],["Failure handling","Record actionable context|Alert on exhausted retries|Replay only after fixing the cause|Use dead-letter workflows for external systems"]]],
  ["laravel-docker-production","Laravel with Docker in Production","Build a production Laravel stack with Nginx, PHP-FPM, PostgreSQL or MySQL, Redis, queue workers, and the scheduler.","laravel",["Laravel","Docker","Nginx"],"cloud-devops",[["Container responsibilities","Nginx serves and proxies|PHP-FPM executes application requests|Separate worker and scheduler processes|Use managed or durable data services"],["Image and configuration","Install production dependencies in a build stage|Run as a non-root user where practical|Inject secrets at runtime"],["Operations","Health-check each responsibility|Persist uploads deliberately|Coordinate migrations and rollback"]]],
  ["laravel-api-security","Laravel API Security: A Production Checklist","Secure Laravel APIs with validation, authorization, rate limiting, authentication, CORS, CSRF, query safety, secrets, and audit logging.","laravel",["Laravel security","API","authorization"],"api-development",[["Request boundary","Validate shape and size|Normalize only documented formats|Reject unknown sensitive fields"],["Identity and permission","Authenticate every protected route|Use policies and ownership checks|Rate-limit login and expensive operations"],["Platform controls","Parameterize database access|Set narrow CORS origins|Protect cookie flows from CSRF|Store secrets outside source"],["Logging","Record actor, action, target, outcome, and request ID|Redact credentials and personal data|Protect audit retention"]]],
  ["flutter-application-architecture","Flutter Application Architecture for Large Mobile and Desktop Systems","Organize large Flutter systems with presentation, domain, data, repositories, services, state, routing, offline sync, testing, and responsive UI.","flutter",["Flutter","application architecture","offline first"],"mobile-development",[["Layer responsibilities","Presentation renders state and user intent|Domain models business rules|Data adapters talk to local and remote systems"],["Repositories and services","Repositories present use-case-oriented data access|Services encapsulate protocols|Keep DTOs away from widgets"],["State and routing","Scope state by feature|Model loading, empty, success, and failure explicitly|Guard routes without hiding authorization rules"],["Offline data and sync","Write durable local intent|Queue sync work|Resolve conflicts with server policy|Expose sync status"],["Desktop and mobile differences","Adapt navigation for pointer and touch input|Model file-system and window behavior behind platform services|Test keyboard, focus, resize, and lifecycle behavior"],["Performance and release operations","Profile rebuilds and expensive layouts|Paginate large datasets|Capture sanitized crash diagnostics and release versions"],["Testing and responsive UI","Test rules without Flutter bindings|Widget-test critical flows|Adapt navigation and density for desktop and mobile"]]],
  ["flutter-offline-first","Flutter Offline-First Architecture: Local Data, Sync and Conflicts","Build Flutter apps with a local database, durable sync queue, connectivity awareness, retry, timestamps, conflict handling, and server reconciliation.","flutter",["Flutter","offline first","synchronization"],"mobile-development",[["Local source of interaction","Render from the local database|Commit user intent locally|Assign stable client IDs"],["Sync queue","Store operation type, entity, version, and retry metadata|Process in dependency order|Use idempotency keys"],["Conflict policy","Do not equate latest device timestamp with truth|Use server versions or domain-specific merge rules|Surface conflicts that need a person"]]],
  ["flutter-windows-deployment","Flutter Windows Deployment: Builds, Installers and Versioning","Prepare Flutter Windows release builds, native dependencies, installers, versioning, distribution, updates, and support diagnostics.","flutter",["Flutter Windows","desktop deployment","installer"],"desktop-development",[["Release build","Pin Flutter and package versions|Build in release mode|Test on a clean supported Windows image"],["Native dependencies","Bundle required runtime libraries and plugins|Verify architecture|Keep licenses and notices"],["Installer and distribution","Use an installer tool such as Inno Setup conceptually|Create per-version artifacts|Sign binaries when the distribution model supports it|Provide safe upgrade and uninstall paths"]]],
  ["flutter-erp-architecture","Flutter ERP Architecture for Connected and Offline Business Systems","Design Flutter ERP modules for inventory, sales, purchases, parties, cash, reports, permissions, offline use, and multi-currency records.","flutter",["Flutter ERP","inventory","offline first"],"enterprise-software",[["Module boundaries","Inventory owns stock movement|Sales and purchases own commercial documents|Accounting consumes explicit postings|Reports read stable projections"],["Offline transactions","Use local document IDs|Queue immutable operations|Prevent duplicate posting|Reconcile server versions"],["Permissions and audit","Authorize on the server|Adapt UI for usability, not security|Record changes and approvals"]]],
  ["flutter-multi-currency-accounting","Flutter Multi-Currency Accounting: Preserving Transaction Currency","Model multi-currency ERP data without silently converting normal transactions, and handle explicit exchange operations separately.","flutter",["multi-currency","Flutter ERP","accounting"],"enterprise-software",[["Preserve transaction currency","10,000 AFN remains 10,000 AFN|500 USD remains 500 USD|300 EUR remains 300 EUR|Store amount and currency together"],["Explicit exchange operation","Record source amount and currency|Record destination amount and currency|Store the applied rate, source, time, fees, and rounding|Post both sides atomically"],["Reporting currency","Conversion for reports is a derived view|Use a dated, documented rate source|Do not overwrite original ledger values"]]],
  ["nextjs-production-architecture","Next.js Production Architecture: SEO, APIs, Deployment and Performance","Design a production Next.js App Router application with server and client components, metadata, caching, APIs, auth, Docker, Nginx, CDN, SEO, and performance.","nextjs",["Next.js","App Router","production architecture"],"web-development",[["Server and client boundaries","Render content on the server by default|Add client components only for interaction|Keep secrets and privileged data access server-only"],["Metadata and SEO","Generate canonical metadata per route|Use semantic HTML and JSON-LD|Publish sitemap and robots policies|Optimize meaningful images"],["Caching and APIs","Choose freshness by data contract|Avoid caching personalized responses|Keep Route Handlers narrow|Invalidate by event or tag where appropriate"],["Authentication and security","Validate sessions on the server|Authorize at the data boundary|Use secure cookies|Protect mutations from cross-site abuse"],["Docker, Nginx, and CDN","Use standalone output where appropriate|Proxy correct headers|Cache immutable assets|Health-check the running application"],["Performance","Protect LCP from client-only rendering|Reserve image dimensions|Limit hydration|Measure real-user latency"]]],
  ["nextjs-seo-guide","Next.js SEO Guide: Metadata, Schema, Sitemaps and Performance","Implement Next.js SEO with route metadata, canonicals, Open Graph, JSON-LD, sitemap, robots, server rendering, internal links, and performance.","nextjs",["Next.js SEO","metadata","structured data"],"web-development",[["Page metadata","Write unique titles and descriptions|Set a self-referencing canonical|Generate social cards|Avoid site-wide keyword duplication"],["Structured data","Describe only visible, truthful content|Use BlogPosting and BreadcrumbList for articles|Validate JSON-LD"],["Discovery and rendering","Include canonical pages in sitemap|Allow useful routes in robots|Server-render indexable content|Noindex internal search results"],["Performance and content","Optimize LCP images|Prevent layout shift|Use descriptive internal links|Keep headings logical"]]],
  ["nextjs-laravel-architecture","Next.js and Laravel Architecture: Authentication, APIs and Deployment","Connect a Next.js frontend to Laravel APIs with safe authentication, cookies or tokens, CORS, WebSockets, deployment, and observability.","nextjs",["Next.js","Laravel","full stack"],"web-development",[["Frontend and backend boundary","Laravel owns business rules and data|Next.js owns the web experience and server rendering|Share a versioned API contract"],["Authentication choices","Prefer secure first-party cookies for same-site systems|Use narrowly scoped tokens for distributed clients|Handle CSRF and CORS according to the choice"],["Realtime and deployment","Authenticate private WebSocket channels|Proxy HTTP and upgrades explicitly|Trace requests across both applications"]]],
  ["nextjs-docker-production","Next.js with Docker in Production","Create a multi-stage Next.js container, use standalone output where appropriate, manage runtime environment, health checks, and an Nginx reverse proxy.","nextjs",["Next.js","Docker","Nginx"],"cloud-devops",[["Multi-stage image","Install locked dependencies|Build in a dedicated stage|Copy only standalone runtime and static assets"],["Environment boundary","Build-time public values are not runtime secrets|Inject server secrets at runtime|Validate required configuration on startup"],["Proxy and health","Forward host and protocol headers|Set deliberate timeouts|Expose a lightweight health endpoint|Shut down gracefully"]]],
  ["react-application-architecture","React Application Architecture: Components, State, APIs and Performance","Structure React applications with feature boundaries, state ownership, API clients, hooks, forms, routing, testing, accessibility, and performance.","react",["React","frontend architecture","performance"],"web-development",[["Component boundaries","Prefer small composable units|Keep domain decisions outside visual primitives|Design explicit props"],["State and hooks","Keep state close to its consumers|Separate remote server state from local UI state|Avoid effects for derived values"],["API and forms","Centralize transport concerns|Validate on client for UX and server for trust|Represent pending and error states"],["Testing and performance","Test behavior over implementation|Measure before memoizing|Code-split by route|Preserve accessibility semantics"]]],
  ["docker-production-guide","Docker Production Guide: Images, Containers and Reliable Deployment","Use Docker images, containers, volumes, networks, health checks, Compose, secrets, logging, resource controls, and deployment practices safely.","devops",["Docker","containers","production"],"cloud-devops",[["Image design","Use small trusted bases|Pin important versions|Separate build and runtime|Run with least privilege"],["Data and networking","Persist only intentional state|Use named internal networks|Publish only required ports|Back up and restore volumes"],["Configuration and secrets","Inject runtime configuration|Use a secret manager or protected files|Never bake credentials into layers"],["Health and resources","Test service readiness|Set memory and CPU controls|Handle termination signals|Restart only when recovery is sensible"],["Supply-chain and runtime security","Scan base images and dependencies|Drop unused Linux capabilities|Use read-only filesystems where practical|Patch and rebuild instead of modifying running containers"],["Logging and deployment","Emit to stdout with request IDs|Centralize retention|Build immutable tags|Roll back to a known artifact"]]],
  ["nginx-reverse-proxy","Nginx Reverse Proxy: TLS, WebSockets, Headers and Timeouts","Configure Nginx reverse proxy concepts for TLS termination, upstreams, forwarded headers, WebSockets, timeouts, and security headers.","devops",["Nginx","reverse proxy","WebSockets"],"cloud-devops",[["Proxy boundary","Terminate TLS|Route by host or path|Preserve client and protocol context with trusted forwarded headers"],["WebSockets and timeouts","Forward Upgrade and Connection correctly|Set idle timeouts for the application protocol|Avoid unlimited waits"],["Security headers","Use HSTS only after HTTPS is stable|Set content-type and framing policies|Test CSP against actual resources"]]],
  ["nginx-certbot-https","Nginx and Certbot HTTPS: Certificate Lifecycle and Docker Operations","Operate TLS certificates with Nginx and Certbot, including issuance, renewal, challenge paths, Docker mounts, permissions, and port conflicts.","devops",["Nginx","Certbot","TLS"],"cloud-devops",[["Certificate lifecycle","Prove domain control|Install the full chain|Renew before expiry|Reload Nginx after successful renewal"],["Docker considerations","Share only required certificate paths|Keep private keys read-only|Persist ACME state|Coordinate a renewal container and proxy"],["Common failures","DNS points elsewhere|Port 80 is occupied or blocked|Challenge path is intercepted|File permissions prevent Nginx reading renewed material"]]],
  ["ci-cd-pipeline","CI/CD Pipeline Design: Build, Test, Deploy and Roll Back Safely","Design a delivery pipeline with deterministic builds, tests, security checks, artifacts, staged deployment, verification, and rollback.","devops",["CI/CD","deployment","rollback"],"cloud-devops",[["Build and test","Use locked dependencies|Run static checks and tests|Scan dependencies and images|Fail on meaningful policy violations"],["Artifact promotion","Create once|Sign or checksum artifacts|Promote the same artifact between environments"],["Deployment and rollback","Apply backward-compatible migrations|Use health verification|Retain the previous release|Practice rollback"]]],
  ["github-actions-guide","GitHub Actions Guide: Workflows, Artifacts and Secure Deployment","Build GitHub Actions workflows with events, jobs, steps, least-privilege permissions, secrets, caching, artifacts, environments, and deployment gates.","devops",["GitHub Actions","CI/CD","deployment"],"cloud-devops",[["Workflow structure","Trigger narrowly|Separate validation and deployment jobs|Pin third-party actions to trusted versions"],["Secrets and permissions","Set least-privilege GITHUB_TOKEN permissions|Use environment protection|Prefer short-lived cloud identity federation"],["Cache and artifacts","Cache only reproducible dependencies|Upload immutable build output|Set retention intentionally"]]],
  ["jenkins-ci-cd","Jenkins CI/CD: Pipelines, Agents and Reliable Deployment","Operate Jenkins pipelines with controlled agents, credentials, stages, artifacts, deployment verification, and rollback.","devops",["Jenkins","CI/CD","pipelines"],"cloud-devops",[["Pipeline as code","Keep Jenkinsfile with the application|Use explicit stages|Make failures visible"],["Agents and credentials","Use disposable agents where possible|Scope credentials to jobs and environments|Mask secrets but do not rely on masking alone"],["Deployment","Promote a versioned artifact|Gate production changes|Verify health|Roll back without rebuilding"]]],
  ["aws-ec2-application-deployment","AWS EC2 Application Deployment: Docker, Nginx, TLS and Operations","Deploy an application to EC2 with a restricted security group, Docker, Nginx, TLS, DNS, monitoring, updates, and tested backups.","devops",["AWS EC2","Docker","Nginx"],"cloud-devops",[["Instance and network","Choose capacity from measurements|Restrict inbound ports|Use managed identity instead of static cloud keys"],["Application edge","Run services in containers|Put Nginx at the edge|Issue TLS for validated DNS|Do not expose databases publicly"],["Operations","Ship metrics and logs|Patch the host|Snapshot only as part of a tested backup plan|Document restoration"]]],
  ["microservices-architecture","Microservices Architecture: Boundaries, Communication and Failure Handling","Choose service boundaries, gateways, synchronous or asynchronous communication, queues, data ownership, observability, and distributed-transaction patterns.","software-architecture",["microservices","distributed systems","queues"],"enterprise-software",[["Service boundaries","Align with business capabilities|Give each service clear data ownership|Avoid distributed monolith coupling"],["Communication","Use synchronous calls when an immediate answer is required|Use events for decoupled facts|Version contracts"],["Failure handling","Set timeouts and budgets|Retry only safe operations|Use circuit breaking selectively|Design compensating workflows"],["Observability","Propagate trace and correlation IDs|Measure dependencies|Centralize searchable logs without leaking secrets"]]],
  ["rest-api-design","REST API Design: Resources, Validation and Idempotency","Design REST APIs with clear resources, HTTP semantics, status codes, validation, pagination, filtering, authentication, versioning, and idempotency.","software-architecture",["REST API","HTTP","idempotency"],"api-development",[["Resources and methods","Use nouns for resources|GET reads, POST creates or commands, PUT replaces, PATCH changes, DELETE removes|Document non-CRUD workflows"],["Responses and validation","Use accurate status codes|Return stable error shapes|Validate type, range, relationships, and permission"],["Collections and evolution","Use bounded pagination|Whitelist filters and sorting|Version breaking contract changes"],["Security and idempotency","Authenticate and authorize separately|Rate-limit abuse-prone endpoints|Make retryable writes idempotent"]]],
  ["database-design-enterprise-applications","Database Design for Enterprise Applications","Design enterprise databases with normalization, indexes, constraints, transactions, foreign keys, audit history, soft deletes, and reporting models.","databases",["database design","SQL","enterprise software"],"enterprise-software",[["Model and constraints","Normalize transactional facts|Use foreign keys|Encode uniqueness and valid ranges|Avoid ambiguous nullable state"],["Transactions and concurrency","Keep transactions short|Choose isolation deliberately|Lock the smallest necessary scope|Handle conflicts"],["Indexes and reporting","Index proven access paths|Inspect query plans|Build reporting projections instead of damaging the write model"],["History and deletion","Use audit events for important changes|Soft-delete only where recovery semantics are real|Respect retention and privacy requirements"]]],
  ["redis-production-guide","Redis in Production: Cache, Sessions, Queues and Failure Handling","Use Redis for cache, sessions, queues, pub/sub, TTLs, and persistence while planning memory limits, eviction, outages, and recovery.","databases",["Redis","cache","queues"],"cloud-devops",[["Choose the role","Cache data can be rebuilt|Sessions affect user continuity|Queues carry work|Pub/sub does not provide durable replay"],["TTL and memory","Set TTLs intentionally|Choose eviction policy for the workload|Prevent unbounded keys|Monitor fragmentation and latency"],["Persistence and failure","Understand RDB and AOF trade-offs|Do not call a cache the system of record|Design application behavior for Redis unavailability"]]],
  ["software-architecture-guide","Software Architecture Guide: Monoliths, Microservices and Trade-offs","Compare monolith, modular monolith, microservices, and event-driven architecture through boundaries, scalability, consistency, operations, and complexity.","software-architecture",["software architecture","modular monolith","microservices"],"enterprise-software",[["Monolith and modular monolith","One deployment can remain well structured|Modules create enforceable internal boundaries|Transactions and local debugging stay simpler"],["Microservices","Independent deployment can fit autonomous capabilities|Network and data consistency costs are real|Operational maturity is a prerequisite"],["Event-driven systems","Events represent completed facts|Consumers must tolerate duplication and ordering limits|Schemas require governance"],["Choosing deliberately","Start from team and domain constraints|Scale measured bottlenecks|Prefer the least complex architecture that meets reliability needs"]]],
];

for (const [slug,title,description,category,tags,relatedService,raw] of supporting) {
  definitions.push({ slug, title, description, excerpt: description, category, tags, relatedService,
    outline: raw.map(([heading, packed]) => [heading, packed.split("|")]) as [string,string[]][],
  });
}

export const ARTICLES: Article[] = definitions.map(makeArticle);
export const getArticle = (slug: string) => ARTICLES.find((article) => article.slug === slug);
export const getCategory = (slug: string) => BLOG_CATEGORIES.find((category) => category.slug === slug);
export const readingTime = (article: Article) => {
  const words = [article.title, article.excerpt, ...article.sections.flatMap((s) => [s.title, ...s.paragraphs, ...(s.bullets ?? [])]), ...article.faqs.flatMap((f) => [f.question, f.answer])].join(" ").split(/\s+/).length;
  return Math.max(4, Math.ceil(words / 210));
};
